app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// Grupo de rotas para o backoffice
Route::group(['prefix' => 'backoffice', 'as' => 'backoffice.', 'middleware' => 'auth'], function () {
    //Rota que mostra o dashboard
    Route::get('', function() {
        $title = "Dashboard";
       return view('backoffice.dashboard', compact('title'));
    });
    // Grupo de rotas para o CRUD de categorias no backoffice
    Route::group(['prefix' => 'categorias', 'as' => 'categories.', 'middleware' => 'web'], function () {
        Route::get('', ['as' => 'index', 'uses' => 'Backoffice\CategoryController@index']);
        Route::get('adicionar', ['as' => 'create', 'uses' => 'Backoffice\CategoryController@create']);
        Route::post('guardar', ['as' => 'store', 'uses' => 'Backoffice\CategoryController@store']);
        Route::get('editar/{id}', ['as' => 'edit', 'uses' => 'Backoffice\CategoryController@edit']);
        Route::post('alterar/{id}', ['as' => 'update', 'uses' => 'Backoffice\CategoryController@update']);
        Route::get('remover/{id}', ['as' => 'destroy', 'uses' => 'Backoffice\CategoryController@destroy']);
    });
    // Grupo de rotas para o CRUD de notícias no backoffice
    Route::group(['prefix' => 'noticias', 'as' => 'news.', 'middleware' => 'web'], function () {
        Route::get('', ['as' => 'index', 'uses' => 'Backoffice\NewsController@index']);
        Route::get('adicionar', ['as' => 'create', 'uses' => 'Backoffice\NewsController@create']);
        Route::post('guardar', ['as' => 'store', 'uses' => 'Backoffice\NewsController@store']);
        Route::get('editar/{id}', ['as' => 'edit', 'uses' => 'Backoffice\NewsController@edit']);
        Route::post('alterar/{id}', ['as' => 'update', 'uses' => 'Backoffice\NewsController@update']);
        Route::get('remover/{id}', ['as' => 'destroy', 'uses' => 'Backoffice\NewsController@destroy']);
    });
    // Grupo de rotas para banners
    Route::group(['prefix' => 'noticias/banner/{id}', 'as' => 'banner.', 'middleware' => 'web'], function () {
        Route::get('', ['as' => 'index', 'uses' => 'Backoffice\BannerController@index']);
        Route::post('guardar', ['as' => 'store', 'uses' => 'Backoffice\BannerController@store']);
        Route::get('remover', ['as' => 'destroy', 'uses' => 'Backoffice\BannerController@destroy']);
    });
});

// Grupo de rotas para o site
Route::group(['prefix' => '', 'as' => 'site.', 'middleware' => 'web'], function () {
    Route::get('', ['as' => 'home', 'uses' => 'Site\HomeController@index']);
    Route::post('newsletter', ['as' => 'newsletter', 'uses' => 'Site\NewsletterController@store']);
    Route::post('commentario/{news_id}', ['as' => 'comment', 'uses' => 'Site\CommentController@store']);
    Route::get('noticias/{category_id}/{category}', ['as' => 'index', 'uses' => 'Site\PageController@index']);
    Route::get('noticias/{category_id}/{category}/{slug}', ['as' => 'show', 'uses' => 'Site\PageController@show']);
});

Route::auth();

resources/views/layout.blade.php
<!DOCTYPE html>
<html>

<head>
    <title>{{ $title or 'Backoffice' }}</title>
    {{-- Styles --}}
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
    @yield('css')
    {{-- Fonts --}}
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">
</head>

<body>
    <div class="container">
        <li class="btn btn-dafault pull-right"><a href="{{ url('/logout') }}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
        @yield('content')
    </div>
    {{-- Javascript --}}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    @yield('js')
</body>

</html>

resources/views/site-layout.blade.php
<!DOCTYPE html>
<html>

<head>
    <title>{{ $title or 'FLAG News' }}</title>
    {{-- Styles --}}
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('css/style.css') }}">
    @yield('css')
    {{-- Fonts --}}
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">
</head>

<body>
<header class="navbar navbar-inverse navbar-fixed-top" role="banner">
    <div class="container">
        <div class="navbar-header">
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" title="Home" href="{{ route('site.home') }}">Home</a>
        </div>
        <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
            <ul class="nav navbar-nav">
                @foreach($categories as $category)
                    <li>
                        <a title="{{ $category->name }}" href="{{ route('site.index', [$category->id, $category->slug]) }}">{{ $category->name }}</a>
                    </li>
                @endforeach
            </ul>
        </nav>
    </div>
</header>

<div class="container">
    @yield('content')
</div>

<footer id="footer">
    <div class="container">
        <p class="footer-p">
            Copyright © 2016 FLAG News
        </p>
    </div>
</footer>
{{-- Javascript --}}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
@yield('js')
</body>

</html>