app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// Grupo de rotas para o backoffice
Route::group(['prefix' => 'backoffice', 'as' => 'backoffice.', 'middleware' => 'auth'], function () {
    //Rota que mostra o dashboard
    Route::get('', function() {
        $title = "Dashboard";
       return view('backoffice.dashboard', compact('title'));
    });
    // Grupo de rotas para o CRUD de categorias no backoffice
    Route::group(['prefix' => 'categorias', 'as' => 'categories.', 'middleware' => 'web'], function () {
        Route::get('', ['as' => 'index', 'uses' => 'Backoffice\CategoryController@index']);
        Route::get('adicionar', ['as' => 'create', 'uses' => 'Backoffice\CategoryController@create']);
        Route::post('guardar', ['as' => 'store', 'uses' => 'Backoffice\CategoryController@store']);
        Route::get('editar/{id}', ['as' => 'edit', 'uses' => 'Backoffice\CategoryController@edit']);
        Route::post('alterar/{id}', ['as' => 'update', 'uses' => 'Backoffice\CategoryController@update']);
        Route::get('remover/{id}', ['as' => 'destroy', 'uses' => 'Backoffice\CategoryController@destroy']);
    });
    // Grupo de rotas para o CRUD de notícias no backoffice
    Route::group(['prefix' => 'noticias', 'as' => 'news.', 'middleware' => 'web'], function () {
        Route::get('', ['as' => 'index', 'uses' => 'Backoffice\NewsController@index']);
        Route::get('adicionar', ['as' => 'create', 'uses' => 'Backoffice\NewsController@create']);
        Route::post('guardar', ['as' => 'store', 'uses' => 'Backoffice\NewsController@store']);
        Route::get('editar/{id}', ['as' => 'edit', 'uses' => 'Backoffice\NewsController@edit']);
        Route::post('alterar/{id}', ['as' => 'update', 'uses' => 'Backoffice\NewsController@update']);
        Route::get('remover/{id}', ['as' => 'destroy', 'uses' => 'Backoffice\NewsController@destroy']);
    });
    // Grupo de rotas para banners
    Route::group(['prefix' => 'noticias/banner/{id}', 'as' => 'banner.', 'middleware' => 'web'], function () {
        Route::get('', ['as' => 'index', 'uses' => 'Backoffice\BannerController@index']);
        Route::post('guardar', ['as' => 'store', 'uses' => 'Backoffice\BannerController@store']);
        Route::get('remover', ['as' => 'destroy', 'uses' => 'Backoffice\BannerController@destroy']);
    });
});

// Grupo de rotas para o site
Route::group(['prefix' => '', 'as' => 'site.', 'middleware' => 'web'], function () {
    Route::get('', ['as' => 'home', 'uses' => 'Site\HomeController@index']);
    Route::post('newsletter', ['as' => 'newsletter', 'uses' => 'Site\NewsletterController@store']);
    Route::post('commentario/{news_id}', ['as' => 'comment', 'uses' => 'Site\CommentController@store']);
    Route::get('noticias/{category_id}/{category}', ['as' => 'index', 'uses' => 'Site\PageController@index']);
    Route::get('noticias/{category_id}/{category}/{slug}', ['as' => 'show', 'uses' => 'Site\PageController@show']);
});

Route::auth();

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    use SoftDeletes;

    /**
     * Os atributos que devem ser mutated para datas.
     *
     * @var array
     */
    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at'
    ];

    /**
     * Os atributos que são mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'slug',
        'category_id'
    ];

    /**
     * Método da relação de uma categoria com ela mesmo (uma categoria pode pertencer a outra categoria).
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function categoryFather ()
    {
        return $this->belongsTo(Category::class, 'category_id');    
    }

    /**
     * Método da relação de uma categoria com ela mesmo (uma categoria pode ter muitas categorias).
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function categoryChild()
    {
        return $this->hasMany(Category::class, 'category_id');
    }

    /**
     * Método da relação de uma categoria com uma notícia (uma categoria pode ter muitas notícias).
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function news()
    {
        return $this->hasMany(News::class, 'category_id', 'id');
    }
}

app/Http/Controllers/Backoffice/BannerController.php
<?php

namespace App\Http\Controllers\Backoffice;

use App\News;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Intervention\Image\Facades\Image;

class BannerController extends Controller
{
    public function index($id)
    {
        $title = "Banner da Notícia";
        $news = News::findOrFail($id);

        $banner = !empty($news->banner) ? $news->banner : null;

        return view('backoffice.banner.index', compact('news', 'banner', 'title'));
    }

    public function store(Request $request, $id)
    {
        $image = $this->upload($request->file('banner'), $id);

        News::findOrFail($id)->update($image);

        return redirect()->back();
    }

    public function destroy($id)
    {
        $delete = ['banner' => null];

        $news = News::findOrFail($id);

        unlink(public_path("images/news/{$news->id}/{$news->banner}"));
        unlink(public_path("images/news/{$news->id}/thumbs/{$news->banner}"));
        rmdir(public_path("images/news/{$news->id}/thumbs"));
        rmdir(public_path("images/news/{$news->id}"));

        $news->update($delete);

        return redirect()->back();
    }

    public function upload($file, $id)
    {
        $image_path = public_path("images/news/{$id}");

        if (!is_dir($image_path . "/thumbs")) {
            mkdir($image_path . "/thumbs", 0777, true);
        }

        $news = News::findOrFail($id);

        $new_name = "{$news->slug}.{$file->getClientOriginalExtension()}";

        $image = Image::make($file)->save("{$image_path}/{$new_name}");

        $image->resize(600, 400, function ($constraint) {
            $constraint->aspectRatio();
        })->save("{$image_path}/thumbs/{$new_name}");

        return ['banner' => $new_name];
    }
}

app/Http/Controllers/Backoffice/CategoryController.php
<?php

namespace App\Http\Controllers\Backoffice;

use App\Category;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Illuminate\Support\Str;

class CategoryController extends Controller
{
    /**
     * Mostra uma lista de categorias.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index ()
    {
        $title = "Lista das Categorias";
        $categories = Category::with('categoryFather')->latest()->paginate(10);

        return view('backoffice.categories.index', compact('categories', 'title'));
    }

    /**
     * Mostra o formulário para criar uma nova categoria.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create ()
    {
        $title = "Registo de Categorias";
        $categories = Category::lists('name', 'id');

        return view('backoffice.categories.create', compact('categories', 'title'));
    }

    /**
     * Guarda a nova categoria na base de dados.
     *
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store (Request $request)
    {
        $this->validate($request, [
            'name' => 'required|max:15',
        ]);

        $request['slug'] = Str::slug($request['name']);
        $request['category_id'] = (empty($request['category_id']) ? null : $request['category_id']);
        Category::create($request->all());

        return redirect()->route('backoffice.categories.index');
     }

    /**
     * Mostra o formulário para editar uma categoria específica.
     *
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit ($id)
    {
        $title = "Edição de Categorias";
        $category = Category::findOrFail($id);
        $categories = Category::where('id', '!=', $id)->get()->lists('name', 'id');

        return view('backoffice.categories.edit', compact('category', 'categories', 'title'));
    }

    /**
     * Atualiza uma categoria específica na base de dados.
     *
     * @param Request $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update (Request $request, $id)
    {
        $request['slug'] = Str::slug($request['name']);
        $request['category_id'] = (empty($request['category_id']) ? null : $request['category_id']);

        $this->validate($request, [
            'name' => 'required|max:15'
        ]);

        Category::findOrFail($id)->update($request->all());

        return redirect()->route('backoffice.categories.index');
    }

    /**
     * Faz soft delete em uma cateforia específica.
     *
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy ($id)
    {
        Category::find($id)->delete();

        return redirect()->back();
    }
}

app/Http/Controllers/Backoffice/NewsController.php
<?php

namespace App\Http\Controllers\Backoffice;

use App\Category;
use App\News;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Illuminate\Support\Str;

class NewsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $title = "Lista de Notícias";
        $news = News::with('category')->latest()->paginate(10);

        return view('backoffice.news.index', compact('news', 'title'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $title = "Registo de Notícias";
        $categories = Category::lists('name', 'id');

        return view('backoffice.news.create', compact('title', 'categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request['slug'] = Str::slug($request['title']);
        $request['category_id'] = (empty($request['category_id']) ? null : $request['category_id']);

        $this->validate($request, [
            'title' => 'required|min:5',
            'summary' => 'required|max:255',
            'description' => 'required'
        ]);

        $news = News::create($request->all());

        return redirect()->route('backoffice.banner.index', $news->id);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $title = "Edição de Notícias";
        $news = News::findOrFail($id);
        $categories = Category::lists('name', 'id');

        return view('backoffice.news.edit', compact('news', 'categories', 'title'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request['slug'] = Str::slug($request['title']);
        $request['category_id'] = (empty($request['category_id']) ? null : $request['category_id']);
        $this->validate($request, [
            'title' => 'required|min:5',
            'summary' => 'required|max:255',
            'description' => 'required',
            'category_id' => 'required'
        ]);

        News::findOrFail($id)->update($request->all());

        return redirect()->route('backoffice.banner.index', $id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        News::find($id)->delete();

        return redirect()->back();
    }
}

resources/views/backoffice/categories/create.blade.php
@extends('layout')

@section('content')
    <div class="row">
        <div class="col-xs-10">
            <h2>Criar Categoria</h2>
        </div>
    </div>
    <hr>

    <a href="{{ route('backoffice.categories.index') }}" class="btn btn-primary">
        <i class="fa fa-reply"></i>
        &nbsp;Voltar
    </a><br><br>

    {!! Form::open(['route'=>'backoffice.categories.store']) !!}
        @include('backoffice.categories.form')<br>
        <div class="col-xs-5 col-sm-4 col-md-3 col-lg-3">
            <button type="submit" class="btn btn-block btn-primary">
                <i class="fa fa-floppy-o"></i>
                &nbsp;Adicionar
            </button>
        </div>
    {!! Form::close() !!}



@endsection

resources/views/backoffice/categories/edit.blade.php
@extends('layout')

@section('content')
    <div class="row">
        <div class="col-xs-10">
            <h2>Editar Categoria</h2>
        </div>
    </div>
    <hr>

    <a href="{{ route('backoffice.categories.index') }}" class="btn btn-primary">
        <i class="fa fa-reply"></i>
        &nbsp;Voltar
    </a><br><br>

    {!! Form::model($category, ['route'=>['backoffice.categories.update', $category->id]]) !!}
        @include('backoffice.categories.form')<br>
        <div class="col-xs-5 col-sm-4 col-md-3 col-lg-3">
            <button type="submit" class="btn btn-block btn-primary">
                <i class="fa fa-floppy-o"></i>
                &nbsp;Gravar
            </button>
        </div>
    {!! Form::close() !!}



@endsection

resources/views/backoffice/categories/form.blade.php
@if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<div class="col-xs-12 col-md-4 col-lg-4">
    <div class="form-group">
        {!! Form::label('name', 'Nome da Categoria') !!}
        {!! Form::text('name', null, ['class'=>'form-control']) !!}
    </div>
</div>

<div class="col-xs-12 col-md-4 col-lg-4">
    <div class="form-group">
        {!! Form::label('category_id', 'Categoria Pai') !!}
        {!! Form::select('category_id', $categories, null, ['class'=>'form-control', 'placeholder'=> 'Escolha...']) !!}
    </div>
</div>

resources/views/backoffice/categories/index.blade.php
@extends('layout')

@section('content')
    <div class="row">
        <div class="col-xs-10">
            <h2>Categorias</h2>
        </div>
    </div>
    <hr>

    <a href="{{ route('backoffice.categories.create') }}" class="btn btn-primary">
        <i class="fa fa-plus"></i>
            &nbsp;Adicionar
    </a>
    <a href="{{ route('backoffice.') }}" class="btn btn-primary pull-right">
        <i class="fa fa-reply"></i>
        &nbsp;Voltar para o dashboard
    </a><br><br>

    <div class="table-list table-responsive">
        <table class="table table-striped table-hover">
            <thead>
                <th>Categoria</th>
                <th>Categoria Pai</th>
            </thead>
            <tbody>
            @forelse($categories as $category)
                <tr>
                    <td>{{ $category->name }}</td>
                    <td>{{ $category->categoryFather['name'] }}</td>
                    <td class="col-xs-2">
                        <div class="btn-group">
                            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                Ações <span class="caret"></span>
                            </button>

                            <ul class="dropdown-menu" role="menu" style="min-width: initial;">
                                <li>
                                    <a href="{{route('backoffice.categories.edit', ['id' => $category->id])}}">Editar</a>
                                </li>
                                <li>
                                    <a href="{{route('backoffice.categories.destroy', ['id' => $category->id])}}">Excluir</a>
                                </li>
                            </ul>
                        </div>
                    </td>
                    @empty
                        <div class="alert alert-info">
                            <i class="fa fa-info-circle"></i>
                            &nbsp;Não há categorias adicionadas.
                        </div>
                    @endforelse
                </tr>
            </tbody>
        </table>
    </div>

@endsection