app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// Grupo de rotas para o backoffice
Route::group(['prefix' => 'backoffice', 'as' => 'backoffice.', 'middleware' => 'auth'], function () {
    //Rota que mostra o dashboard
    Route::get('', function() {
        $title = "Dashboard";
       return view('backoffice.dashboard', compact('title'));
    });
    // Grupo de rotas para o CRUD de categorias no backoffice
    Route::group(['prefix' => 'categorias', 'as' => 'categories.', 'middleware' => 'web'], function () {
        Route::get('', ['as' => 'index', 'uses' => 'Backoffice\CategoryController@index']);
        Route::get('adicionar', ['as' => 'create', 'uses' => 'Backoffice\CategoryController@create']);
        Route::post('guardar', ['as' => 'store', 'uses' => 'Backoffice\CategoryController@store']);
        Route::get('editar/{id}', ['as' => 'edit', 'uses' => 'Backoffice\CategoryController@edit']);
        Route::post('alterar/{id}', ['as' => 'update', 'uses' => 'Backoffice\CategoryController@update']);
        Route::get('remover/{id}', ['as' => 'destroy', 'uses' => 'Backoffice\CategoryController@destroy']);
    });
    // Grupo de rotas para o CRUD de notícias no backoffice
    Route::group(['prefix' => 'noticias', 'as' => 'news.', 'middleware' => 'web'], function () {
        Route::get('', ['as' => 'index', 'uses' => 'Backoffice\NewsController@index']);
        Route::get('adicionar', ['as' => 'create', 'uses' => 'Backoffice\NewsController@create']);
        Route::post('guardar', ['as' => 'store', 'uses' => 'Backoffice\NewsController@store']);
        Route::get('editar/{id}', ['as' => 'edit', 'uses' => 'Backoffice\NewsController@edit']);
        Route::post('alterar/{id}', ['as' => 'update', 'uses' => 'Backoffice\NewsController@update']);
        Route::get('remover/{id}', ['as' => 'destroy', 'uses' => 'Backoffice\NewsController@destroy']);
    });
    // Grupo de rotas para banners
    Route::group(['prefix' => 'noticias/banner/{id}', 'as' => 'banner.', 'middleware' => 'web'], function () {
        Route::get('', ['as' => 'index', 'uses' => 'Backoffice\BannerController@index']);
        Route::post('guardar', ['as' => 'store', 'uses' => 'Backoffice\BannerController@store']);
        Route::get('remover', ['as' => 'destroy', 'uses' => 'Backoffice\BannerController@destroy']);
    });
});

// Grupo de rotas para o site
Route::group(['prefix' => '', 'as' => 'site.', 'middleware' => 'web'], function () {
    Route::get('', ['as' => 'home', 'uses' => 'Site\HomeController@index']);
    Route::post('newsletter', ['as' => 'newsletter', 'uses' => 'Site\NewsletterController@store']);
    Route::post('commentario/{news_id}', ['as' => 'comment', 'uses' => 'Site\CommentController@store']);
    Route::get('noticias/{category_id}/{category}', ['as' => 'index', 'uses' => 'Site\PageController@index']);
    Route::get('noticias/{category_id}/{category}/{slug}', ['as' => 'show', 'uses' => 'Site\PageController@show']);
});

Route::auth();

app/Http/Controllers/Site/CommentController.php
<?php

namespace App\Http\Controllers\Site;

use App\Comment;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class CommentController extends Controller
{
    public function store(Request $request, $news_id)
    {
        $this->validate($request, [
            'name' => 'required|min:3',
            'email' => 'required|email',
            'description' => 'required|max:255'
        ]);

        Comment::create($request->all());

        return redirect()->back();
    }
}

app/Http/Controllers/Site/HomeController.php
<?php

namespace App\Http\Controllers\Site;

use App\Category;
use App\News;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class HomeController extends Controller
{
    public function index()
    {
        $title = "FLAG News | Home";
        $categories = Category::all();
        $news = News::with('category')->latest()->take(10)->get();

        return view ('site.home.index', compact('title', 'categories', 'news'));
    }
}

app/Http/Controllers/Site/NewsletterController.php
<?php

namespace App\Http\Controllers\Site;

use App\Newsletter;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class NewsletterController extends Controller
{
    public function store(Request $request)
    {

        $this->validate($request, [
            'name' => 'required|min:3',
            'email' => 'required|email',
        ]);

        Newsletter::create($request->all());

        return redirect()->back();
    }
}

app/Http/Controllers/Site/PageController.php
<?php

namespace App\Http\Controllers\Site;

use App\Category;
use App\Comment;
use App\News;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class PageController extends Controller
{
    public function index($category_id, $category)
    {
        $categories = Category::all();
        $category = Category::findOrFail($category_id);
        $title = "FLAG News | {$category->name}";
        $news = News::with('category')->where('category_id', '=', $category_id )->latest()->paginate(10);

        return view('site.page.index', compact('categories', 'category', 'news', 'title'));
    }

    public function show($category_id, $category, $slug)
    {
        $categories = Category::all();
        $category = Category::findOrFail($category_id);
        $news = News::with('category')->where('slug', '=', $slug)->first();
        $title = $news->title;
        $comments = Comment::where('news_id', '=', $news->id)->latest()->get();

        return view('site.page.show', compact('news', 'title', 'categories', 'category', 'comments'));
    }
}

resources/views/site/page/comment.blade.php
@if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
<div class="container">
    {!! Form::open(['route' => ['site.comment', $news->id]]) !!}
    <input type="hidden" name="news_id" value="{{$news->id}}">

    <div class="col-xs-12 col-md-6 col-lg-6">
        <div class="form-group">
            {!! Form::label('name', 'Nome') !!}
            {!! Form::text('name', null, ['class'=>'form-control', 'placeholder'=>'Insira o seu nome']) !!}
        </div>
    </div>

    <div class="col-xs-12 col-md-6 col-lg-6">
        <div class="form-group">
            {!! Form::label('email', 'Email') !!}
            {!! Form::text('email', null, ['class'=>'form-control', 'placeholder'=> 'Insira o seu email']) !!}
        </div>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            {!! Form::label('description', 'Comentário') !!}
            {!! Form::textarea('description', null, ['class' => 'form-control', 'placeholder'=> 'Insira o seu comentário', 'rows' => '3']) !!}
        </div>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-2 col-lg-2">
        <div class="form-group">
            <button type="submit" class="btn btn-block btn-primary">
                <i class=" fa fa-paper-plane"></i>
                &nbsp;Submeter
            </button>
        </div>
    </div>
    {!! Form::close() !!}
</div>
<hr>

@forelse($comments as $comment)
<div class="container col-xs-12 col-sm-12 col-md-12 col-lg-12 comments">
    <div class="col-xs-12 col-md-10 col-lg-10">
        <strong>{{ $comment->name }}</strong>&nbsp;&nbsp;
        <small class="detail">{{ $comment->email }}</small>
    </div>
    <small class="col-xs-12 col-md-2 col-lg-2 detail">{{ $comment->created_at }}</small>
    <br><br>
    <div class="col-xs-12 col-md-12 col-lg-12">
        {{ $comment->description }}
    </div>
</div>
<hr>
@empty
<div class="alert alert-info">Esta notícia não tem comentários</div>
@endforelse

resources/views/site/page/index.blade.php
@extends('site-layout')

@section('content')

    <div id="header-wrapper" class="container">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4 head-col">
            <div class="titlewrapper">
                <h1>
                    <a href="" title="Flag News">{{ $category->name }}</a>
                </h1>
            </div>
        </div>
    </div>

    <div class="main-wrapper">
        <div class="container main-container">
            <div class="row main-index">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 main-post-col">
                    <div class="thumbnails">
                        @forelse($news as $new)
                            <div class="entry row">
                                <div class="post-content">
                                    <div class="col-lg-4 col-md-4">
                                        <a class="thumbnail ajax_link" title="{{ $new->title }}" href="{{ route('site.show', [$category->id, $category->slug, $new->slug]) }}">
                                            <img class="clearfix img-responsive" alt="{{ $new->title }}" title="{{ $new->title }}" src="{{ asset("/images/news/{$new->id}/thumbs/{$new->banner}") }}"/></a>
                                    </div>

                                    <div class="col-lg-8 col-md-8">
                                        <div class="content-row caption">
                                            <h2 class="post-title-h2"><a href="{{ route('site.show', [$category->id, $category->slug, $new->slug]) }}" title="{{ $new->title }}">
                                                    {{ $new->title }}
                                                </a>
                                            </h2>
                                        </div>

                                        <div>
                                            {{ $new->summary }}
                                        </div>
                                    </div>

                                    <div class="col-lg-12 col-md-12">
                                        <div class="post-meta-home">
                                            <span class="pull-left">
                                                <span class="date-meta meta-elements">
                                                     {{ $new->created_at }}
                                                </span>
                                                <span class="tag-meta meta-elements">
                                                    <a class="btn btn-success" href="{{ route('site.index', [$category->id, $category->slug]) }}">
                                                        {{ $category->name }}
                                                    </a>
                                                </span>
                                            </span>

                                            <span class="pull-right">
                                                <a class="btn btn-primary" href="{{ route('site.show', [$category->id, $category->slug, $new->slug]) }}">
                                                    Read More
                                                </a>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        @empty
                            <div class="alert alert-info">Não existem notícias</div>
                        @endforelse
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="row text-center">
                    {!! $news->render() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/site/page/show.blade.php
@extends('site-layout')

@section('content')
    <div id="header-wrapper" class="container">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4 head-col">
            <div class="titlewrapper">
                <h1>
                    <a href="{{ route('site.index', [$category->id, $category->slug]) }}" title="Flag News">{{ $category->name }}</a>
                </h1>
            </div>
        </div>
    </div>

    <div class="main-wrapper">
        <div class="container main-container">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 main-post-col">
                    <div class="post-p-heading">
                        <h1 class="main-heading-post">
                            {{ $news->title }}
                        </h1>
                    </div>

                    <div class="post-meta-post">
        			    <span class="pull-left">
                            <span>
                      	        <a class="btn btn-info btn-sm" href="{{ route('site.index', [$category->id, $category->slug]) }}">{{ $category->name }}</a>
                            </span>
                        </span>
                    </div>

                    <div class="page-post">
                        <img class="clearfix img-responsive" alt="{{ $news->title }}" title="{{ $news->title }}" src="{{ asset("/images/news/{$news->id}/{$news->banner}") }}"/></a>
                    </div>

                    <div class="page-post page-description">
                        <p>{!! $news->description !!}</p>
                    </div>
                    <hr>

                    <span>
                        <a class="btn btn-info btn-sm" href="{{ route('site.index', [$category->id, $category->slug]) }}">{{ $category->name }}</a>
                    </span>
                    <hr>
                    @include('site.page.comment')
                </div>
            </div>
        </div>
    </div>

@endsection