app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// Grupo de rotas para o backoffice
Route::group(['prefix' => 'backoffice', 'as' => 'backoffice.', 'middleware' => 'auth'], function () {
    //Rota que mostra o dashboard
    Route::get('', function() {
        $title = "Dashboard";
       return view('backoffice.dashboard', compact('title'));
    });
    // Grupo de rotas para o CRUD de categorias no backoffice
    Route::group(['prefix' => 'categorias', 'as' => 'categories.', 'middleware' => 'web'], function () {
        Route::get('', ['as' => 'index', 'uses' => 'Backoffice\CategoryController@index']);
        Route::get('adicionar', ['as' => 'create', 'uses' => 'Backoffice\CategoryController@create']);
        Route::post('guardar', ['as' => 'store', 'uses' => 'Backoffice\CategoryController@store']);
        Route::get('editar/{id}', ['as' => 'edit', 'uses' => 'Backoffice\CategoryController@edit']);
        Route::post('alterar/{id}', ['as' => 'update', 'uses' => 'Backoffice\CategoryController@update']);
        Route::get('remover/{id}', ['as' => 'destroy', 'uses' => 'Backoffice\CategoryController@destroy']);
    });
    // Grupo de rotas para o CRUD de notícias no backoffice
    Route::group(['prefix' => 'noticias', 'as' => 'news.', 'middleware' => 'web'], function () {
        Route::get('', ['as' => 'index', 'uses' => 'Backoffice\NewsController@index']);
        Route::get('adicionar', ['as' => 'create', 'uses' => 'Backoffice\NewsController@create']);
        Route::post('guardar', ['as' => 'store', 'uses' => 'Backoffice\NewsController@store']);
        Route::get('editar/{id}', ['as' => 'edit', 'uses' => 'Backoffice\NewsController@edit']);
        Route::post('alterar/{id}', ['as' => 'update', 'uses' => 'Backoffice\NewsController@update']);
        Route::get('remover/{id}', ['as' => 'destroy', 'uses' => 'Backoffice\NewsController@destroy']);
    });
    // Grupo de rotas para banners
    Route::group(['prefix' => 'noticias/banner/{id}', 'as' => 'banner.', 'middleware' => 'web'], function () {
        Route::get('', ['as' => 'index', 'uses' => 'Backoffice\BannerController@index']);
        Route::post('guardar', ['as' => 'store', 'uses' => 'Backoffice\BannerController@store']);
        Route::get('remover', ['as' => 'destroy', 'uses' => 'Backoffice\BannerController@destroy']);
    });
});

// Grupo de rotas para o site
Route::group(['prefix' => '', 'as' => 'site.', 'middleware' => 'web'], function () {
    Route::get('', ['as' => 'home', 'uses' => 'Site\HomeController@index']);
    Route::post('newsletter', ['as' => 'newsletter', 'uses' => 'Site\NewsletterController@store']);
    Route::post('commentario/{news_id}', ['as' => 'comment', 'uses' => 'Site\CommentController@store']);
    Route::get('noticias/{category_id}/{category}', ['as' => 'index', 'uses' => 'Site\PageController@index']);
    Route::get('noticias/{category_id}/{category}/{slug}', ['as' => 'show', 'uses' => 'Site\PageController@show']);
});

Route::auth();

app/News.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class News extends Model
{
    use SoftDeletes;

    /**
     * Os atributos que devem ser mutated para datas.
     *
     * @var array
     */
    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at'
    ];

    /**
     * Os atributos que são mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'banner',
        'title',
        'slug',
        'summary',
        'description',
        'category_id'
    ];

    /**
     * Método da relação de uma notícia com uma categoria (uma notícia tem uma categoria).
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function category()
    {
        return $this->belongsTo(Category::class, 'category_id');
    }

    /**
     * Método da relação de uma noticia com um comentario (uma noticia pode ter muitos comentários).
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function comments ()
    {
        return $this->hasMany(Comment::class, 'news_id', 'id');
    }

    public function getCreatedAtAttribute($date)
    {
        return ($this->attributes['created_at']) ? Carbon::createFromFormat('Y-m-d H:i:s', $date)->format('d/m/Y H:i') : null;
    }

    public function getUpdatedAtAttribute($date)
    {
        return ($this->attributes['updated_at']) ? Carbon::createFromFormat('Y-m-d H:i:s', $date)->format('d/m/Y H:i') : null;
    }
}

app/Http/Controllers/Backoffice/BannerController.php
<?php

namespace App\Http\Controllers\Backoffice;

use App\News;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Intervention\Image\Facades\Image;

class BannerController extends Controller
{
    public function index($id)
    {
        $title = "Banner da Notícia";
        $news = News::findOrFail($id);

        $banner = !empty($news->banner) ? $news->banner : null;

        return view('backoffice.banner.index', compact('news', 'banner', 'title'));
    }

    public function store(Request $request, $id)
    {
        $image = $this->upload($request->file('banner'), $id);

        News::findOrFail($id)->update($image);

        return redirect()->back();
    }

    public function destroy($id)
    {
        $delete = ['banner' => null];

        $news = News::findOrFail($id);

        unlink(public_path("images/news/{$news->id}/{$news->banner}"));
        unlink(public_path("images/news/{$news->id}/thumbs/{$news->banner}"));
        rmdir(public_path("images/news/{$news->id}/thumbs"));
        rmdir(public_path("images/news/{$news->id}"));

        $news->update($delete);

        return redirect()->back();
    }

    public function upload($file, $id)
    {
        $image_path = public_path("images/news/{$id}");

        if (!is_dir($image_path . "/thumbs")) {
            mkdir($image_path . "/thumbs", 0777, true);
        }

        $news = News::findOrFail($id);

        $new_name = "{$news->slug}.{$file->getClientOriginalExtension()}";

        $image = Image::make($file)->save("{$image_path}/{$new_name}");

        $image->resize(600, 400, function ($constraint) {
            $constraint->aspectRatio();
        })->save("{$image_path}/thumbs/{$new_name}");

        return ['banner' => $new_name];
    }
}

app/Http/Controllers/Backoffice/CategoryController.php
<?php

namespace App\Http\Controllers\Backoffice;

use App\Category;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Illuminate\Support\Str;

class CategoryController extends Controller
{
    /**
     * Mostra uma lista de categorias.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index ()
    {
        $title = "Lista das Categorias";
        $categories = Category::with('categoryFather')->latest()->paginate(10);

        return view('backoffice.categories.index', compact('categories', 'title'));
    }

    /**
     * Mostra o formulário para criar uma nova categoria.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create ()
    {
        $title = "Registo de Categorias";
        $categories = Category::lists('name', 'id');

        return view('backoffice.categories.create', compact('categories', 'title'));
    }

    /**
     * Guarda a nova categoria na base de dados.
     *
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store (Request $request)
    {
        $this->validate($request, [
            'name' => 'required|max:15',
        ]);

        $request['slug'] = Str::slug($request['name']);
        $request['category_id'] = (empty($request['category_id']) ? null : $request['category_id']);
        Category::create($request->all());

        return redirect()->route('backoffice.categories.index');
     }

    /**
     * Mostra o formulário para editar uma categoria específica.
     *
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit ($id)
    {
        $title = "Edição de Categorias";
        $category = Category::findOrFail($id);
        $categories = Category::where('id', '!=', $id)->get()->lists('name', 'id');

        return view('backoffice.categories.edit', compact('category', 'categories', 'title'));
    }

    /**
     * Atualiza uma categoria específica na base de dados.
     *
     * @param Request $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update (Request $request, $id)
    {
        $request['slug'] = Str::slug($request['name']);
        $request['category_id'] = (empty($request['category_id']) ? null : $request['category_id']);

        $this->validate($request, [
            'name' => 'required|max:15'
        ]);

        Category::findOrFail($id)->update($request->all());

        return redirect()->route('backoffice.categories.index');
    }

    /**
     * Faz soft delete em uma cateforia específica.
     *
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy ($id)
    {
        Category::find($id)->delete();

        return redirect()->back();
    }
}

app/Http/Controllers/Backoffice/NewsController.php
<?php

namespace App\Http\Controllers\Backoffice;

use App\Category;
use App\News;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Illuminate\Support\Str;

class NewsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $title = "Lista de Notícias";
        $news = News::with('category')->latest()->paginate(10);

        return view('backoffice.news.index', compact('news', 'title'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $title = "Registo de Notícias";
        $categories = Category::lists('name', 'id');

        return view('backoffice.news.create', compact('title', 'categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request['slug'] = Str::slug($request['title']);
        $request['category_id'] = (empty($request['category_id']) ? null : $request['category_id']);

        $this->validate($request, [
            'title' => 'required|min:5',
            'summary' => 'required|max:255',
            'description' => 'required'
        ]);

        $news = News::create($request->all());

        return redirect()->route('backoffice.banner.index', $news->id);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $title = "Edição de Notícias";
        $news = News::findOrFail($id);
        $categories = Category::lists('name', 'id');

        return view('backoffice.news.edit', compact('news', 'categories', 'title'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request['slug'] = Str::slug($request['title']);
        $request['category_id'] = (empty($request['category_id']) ? null : $request['category_id']);
        $this->validate($request, [
            'title' => 'required|min:5',
            'summary' => 'required|max:255',
            'description' => 'required',
            'category_id' => 'required'
        ]);

        News::findOrFail($id)->update($request->all());

        return redirect()->route('backoffice.banner.index', $id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        News::find($id)->delete();

        return redirect()->back();
    }
}

resources/views/backoffice/news/create.blade.php
@extends('layout')

@section('content')
    <div class="row">
        <div class="col-xs-10">
            <h2>Criar Notícia</h2>
        </div>
    </div>
    <hr>

    <a href="{{ route('backoffice.news.index') }}" class="btn btn-primary">
        <i class="fa fa-reply"></i>
        &nbsp;Voltar
    </a><br><br>

    {!! Form::open(['route'=>'backoffice.news.store']) !!}
        @include('backoffice.news.form')<br>
        <div class="col-xs-5 col-sm-4 col-md-3 col-lg-3">
            <button type="submit" class="btn btn-block btn-primary">
                <i class="fa fa-floppy-o"></i>
                &nbsp;Adicionar
            </button>
        </div>
    {!! Form::close() !!}



@endsection

resources/views/backoffice/news/edit.blade.php
@extends('layout')

@section('content')
    <div class="row">
        <div class="col-xs-10">
            <h2>Editar Notícia</h2>
        </div>
    </div>
    <hr>

    <a href="{{ route('backoffice.news.index') }}" class="btn btn-primary">
        <i class="fa fa-reply"></i>
        &nbsp;Voltar
    </a><br><br>

    {!! Form::model($news, ['route'=>['backoffice.news.update', $news->id]]) !!}
        @include('backoffice.news.form')<br>
        <div class="col-xs-5 col-sm-4 col-md-3 col-lg-3">
            <button type="submit" class="btn btn-block btn-primary">
                <i class="fa fa-floppy-o"></i>
                &nbsp;Gravar
            </button>
        </div>
    {!! Form::close() !!}



@endsection

resources/views/backoffice/news/form.blade.php
@if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<div class="col-xs-12 col-sm-12 col-md-12">
    <div class="form-group">
        {!! Form::label('category_id', 'Categoria') !!}
        {!! Form::select('category_id', $categories, null, ['placeholder' => 'Selecione...','class' => 'form-control']) !!}
    </div>
</div>

<div class="col-xs-12 col-sm-12 col-md-4">
    <div class="form-group">
        {!! Form::label('title', 'Título da Notícia') !!}
        {!! Form::text('title', null, ['class' => 'form-control']) !!}
    </div>
</div>

@if(!empty($news))
    <div class="col-xs-12 col-sm-12 col-md-4">
        <div class="form-group">
            {!! Form::label('created_at', 'Data da Notícia') !!}
            {!! Form::text('created_at', null, ['class' => 'form-control', 'disabled']) !!}
        </div>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-4">
        <div class="form-group">
            {!! Form::label('updated_at', 'Última Atualização') !!}
            {!! Form::text('updated_at', null, ['class' => 'form-control', 'disabled']) !!}
        </div>
    </div>
@endif

<div class="col-xs-12 col-sm-12 col-md-12">
    <div class="form-group">
        {!! Form::label('summary', 'Resumo da Notícia') !!}
        {!! Form::textarea('summary', null, ['class' => 'form-control']) !!}
    </div>
</div>

<div class="col-xs-12 col-sm-12 col-md-12">
    <div class="form-group">
        {!! Form::label('description', 'Texto') !!}
        {!! Form::textarea('description', null, ['class' => 'form-control ckeditor', 'id' => 'description']) !!}
    </div>
</div>

@section('js')
    <script src="{{ asset("/other_components/ckeditor/ckeditor.js") }}"></script>
    <script>
        CKEDITOR.replace('description',
                {
                    customConfig : 'config-default.js',
                    toolbarGroups: [
                        {"name":"document","groups":["mode"]},
                        {"name":"basicstyles","groups":["basicstyles"]},
                        {"name":"links","groups":["links"]},
                        {"name":"paragraph","groups":["list","blocks","align"]},
                        {"name":"insert","groups":["insert"]},
                        {"name":"styles","groups":["styles"]},
                    ],
                    removeButtons: 'Strike,Subscript,Superscript,Anchor,Styles,Specialchar'
                }
        );
    </script>
@endsection

resources/views/backoffice/news/index.blade.php
@extends('layout')

@section('content')
    <div class="row">
        <div class="col-xs-10">
            <h2>Notícias</h2>
        </div>
    </div>
    <hr>

    <a href="{{ route('backoffice.news.create') }}" class="btn btn-primary">
        <i class="fa fa-plus"></i>
            &nbsp;Adicionar
    </a>
    <a href="{{ route('backoffice.') }}" class="btn btn-primary pull-right">
        <i class="fa fa-reply"></i>
        &nbsp;Voltar para o dashboard
    </a><br><br>

    <div class="table-list table-responsive">
        <table class="table table-striped table-hover">
            <thead>
                <th>Título</th>
                <th>Resumo</th>
                <th>Categoria</th>
                <th>Criado em:</th>
                <th>Ultima atualização:</th>
            </thead>
            <tbody>
            @forelse($news as $new)
                <tr>
                    <td>{{ $new->title }}</td>
                    <td>{!! str_limit($new->summary, 60) !!}</td>
                    <td>{{ $new->category['name'] }}</td>
                    <td>{{ $new->created_at }}</td>
                    <td>{{ $new->updated_at }}</td>
                    <td class="col-xs-2">
                        <div class="btn-group">
                            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                Ações <span class="caret"></span>
                            </button>

                            <ul class="dropdown-menu" role="menu" style="min-width: initial;">
                                <li>
                                    <a href="{{route('backoffice.news.edit', ['id' => $new->id])}}">Editar</a>
                                </li>
                                <li>
                                    <a href="{{route('backoffice.news.destroy', ['id' => $new->id])}}">Excluir</a>
                                </li>
                            </ul>
                        </div>
                    </td>
                    @empty
                        <div class="alert alert-info">
                            <i class="fa fa-info-circle"></i>
                            &nbsp;Não há notícias adicionadas.
                        </div>
                    @endforelse
                </tr>
            </tbody>
        </table>
        <div class="text-center">
            {{ $news->render() }}
        </div>
    </div>

@endsection